api:
  base_url: "https://api.fda.gov/device/event.json"
  timeout: 30
  max_attempts: 5
  max_retry_delay: 30
  limit : 5

paths:
  raw_data: "data/raw"
  proceesed: "data/proceesed"

product_codes:
  - ESD
  - OSM
  - QUG
  - QUF
  - PLK
  - QDD
  - QUH
  - SCR
  - LRB
  - LDG

schemas:
  events:
    columns:
      - report_number
      - event_type
      - event_location
      - date_of_event
      - date_received
      - date_report
      - report_source_code
      - adverse_event_flag
      - health_professional
      - number_devices_in_event
      - number_patients_in_event
      - manufacturer_name

    required:
      - report_number
      - date_received
      - event_type


  devices:
    columns:
      - report_number
      - device_event_key
      - device_sequence_number
      - brand_name
      - generic_name
      - manufacturer_d_name
      - model_number
      - catalog_number
      - lot_number
      - device_operator
      - device_availability
      - device_report_product_code
      - device_age_text
      - device_evaluated_by_manufacturer
      - implant_flag

    required:
      - report_number
      - device_sequence_number
      - device_report_product_code


  patients:
    columns:
      - report_number
      - patient_sequence_number
      - date_received
      - patient_age
      - patient_sex
      - patient_weight
      - patient_ethnicity
      - patient_race

    required:
      - report_number
      - patient_sequence_number


  mdr_text:
    columns:
      - report_number
      - mdr_text_key
      - text_type_code
      - patient_sequence_number

    required:
      - report_number 
      - mdr_text_key
      - text